# On utilise l'image JDK
FROM eclipse-temurin:17-jdk
WORKDIR /app
COPY . .
RUN chmod +x mvnw
# Compilation du JAR
RUN ./mvnw clean package -DskipTests

# Commande de lancement
ENTRYPOINT ["java", "-jar", "target/BestChoice-0.0.1-SNAPSHOT.jar"]