# Étape 1 : Build
FROM node:20 AS build
WORKDIR /app
COPY bestchoice-front/package*.json ./
RUN npm install
COPY bestchoice-front/ ./
RUN npm run build -- --configuration production

# Étape 2 : Serveur Nginx
FROM nginx:stable-alpine
COPY --from=build /app/dist/bestchoice-front/browser /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]