services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile.backend
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  frontend:
    build:
      context: ./bestchoice-front
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - backend